using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace CodeMechanic.Embeds.SourceGen;

[Generator]
public sealed class EmbeddedResourcesGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // HelloWorld placeholder - no csproj parsing yet
        context.RegisterPostInitializationOutput(static ctx =>
        {
            var source = GenerateHelloWorld();
            ctx.AddSource("CodeMechanic_Embeds_HelloWorld.g.cs",
                SourceText.From(source, Encoding.UTF8));
        });
    }

    private static string GenerateHelloWorld()
    {
        return """
               // <auto-generated />
               #nullable enable

               using System;

               namespace CodeMechanic.Embeds
               {
                   /// <summary>
                   /// CodeMechanic.Embeds.SourceGen is alive and kicking on your BaGetter feed!
                   /// </summary>
                   public static partial class Embedded
                   {
                       public static readonly SourceFile HelloWorldTemplate = new()
                       {
                           Name = "HelloWorld",
                           Qualified = "CodeMechanic.Embeds",
                           Extension = ".template",
                           // FullName will be constructed correctly by your existing logic
                       };

                       static Embedded()
                       {
                           Console.WriteLine("🎉 CodeMechanic.Embeds.SourceGen HelloWorld loaded successfully!");
                       }
                   }
               }
               """;
    }
}
