using System.ComponentModel;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Serialization;

namespace CodeMechanic.Embeds.SourceGen;

[Generator]
public class TemplateFilesGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Get all AdditionalText files
        var templates = context.AdditionalTextsProvider
            .Where(at => at.Path.EndsWith(".template", System.StringComparison.OrdinalIgnoreCase));

        // Map to (path, text)
        var fileContents = templates.Select((additionalText, ct) =>
        {
            var path = additionalText.Path;
            var text = additionalText.GetText(ct)?.ToString() ?? string.Empty;
            return (path, text);
        });

        // Create a generated source per template
        context.RegisterSourceOutput(fileContents, (spc, state) =>
        {
            var (path, text) = state;
            var className = SafeIdentifier(Path.GetFileNameWithoutExtension(path));
            var escaped = EscapeForVerbatimString(text);

            var sb = new StringBuilder();
            sb.AppendLine("namespace GeneratedFromTemplates");
            sb.AppendLine("{");
            sb.AppendLine($"    public static class {className}");
            sb.AppendLine("    {");
            sb.AppendLine($"        public const string Template = @\"{escaped}\";");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            var hintName = $"{className}.g.cs";
            spc.AddSource(hintName, SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }

    static string SafeIdentifier(string raw)
    {
        if (string.IsNullOrEmpty(raw)) return "Template";
        var sb = new StringBuilder();
        foreach (var ch in raw)
            sb.Append(char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_');
        return sb.ToString();
    }

    static string EscapeForVerbatimString(string s) => (s ?? string.Empty).Replace("\"", "\"\"");
}


//
// [Generator]
// public sealed class EmbeddedResourcesGenerator : IIncrementalGenerator
// {
//     private static Assembly my_ass = Assembly.GetExecutingAssembly();
//     private static Assembly your_ass = Assembly.GetCallingAssembly();
//
//     public void Initialize(IncrementalGeneratorInitializationContext context)
//     {
//         context.RegisterPostInitializationOutput(ctx =>
//         {
//             var resources = my_ass.GetManifestResourceNames();
//
//
//             foreach (var resourcename in resources)
//             {
//                 string source_code = my_ass.ReadSourceFile(resources, resourcename);
//
//                 // todo: finish any special replacements here
//
//                 var map = new Dictionary<string, string>()
//                 {
//                     // [@"$foo$"] = "bar"
//                 };
//
//                 // source_code = source_code
//                 //     .Split('\n')
//                 //     .ReplaceAll(map)
//                 //     .Rollup();
//
//                 string template_code = GenerateCode();
//
//                 string hydrated_template = template_code.Split('\n').ReplaceAll(map).Rollup();
//
//                 ctx.AddSource($"{Path.GetFileNameWithoutExtension(resourcename)}.g.cs",
//                     SourceText.From(hydrated_template, Encoding.UTF8));
//             }
//
//             var source = GenerateCode();
//
//             source = new StringBuilder(source).AppendLine($"// resources: {resources.Length}").ToString();
//
//             ctx.AddSource("CodeMechanic_Embeds_Resources.g.cs",
//                 SourceText.From(source, Encoding.UTF8));
//         });
//     }
//
//     private static string GenerateCode()
//     {
//         return """
//                // <auto-generated />
//                #nullable enable
//
//                namespace CodeMechanic.Embeds
//                {
//                    /// <summary>
//                    /// Strongly-typed embedded resource references.
//                    /// Generated by CodeMechanic.Embeds.SourceGen
//                    /// </summary>
//                    public static partial class Embedded
//                    {
//
//                        // I'ma goofy goober
//                        public static readonly SourceFile PackageReferenceTemplate = new()
//                        {
//                            Name = "package_reference.template",
//                            Qualified = "sfapp.templates",
//                            Extension = ".template"
//                        };
//
//                        public static readonly SourceFile RazorAppTemplate = new()
//                        {
//                            Name = "razor.app.template",
//                            Qualified = "sfapp.templates",
//                            Extension = ".template"
//                        };
//
//                        // TODO: Add more templates here as we expand glob parsing
//                    }
//                }
//                """;
//     }
// }

public static class EmbeddedResourceExtensions
{
    private static RegexOptions gmix = RegexOptions.Compiled | RegexOptions.Multiline | RegexOptions.IgnoreCase |
                                       RegexOptions.IgnorePatternWhitespace;

    private static RegexOptions gsix = RegexOptions.Compiled | RegexOptions.Singleline | RegexOptions.IgnoreCase |
                                       RegexOptions.IgnorePatternWhitespace;

    // private static Regex extensions_regex =
    //     new Regex(@"^(?<qualified>.+?)\.(?<name>(?:(?<order>\d+)_)?[^.]+\.(?<extension>\w+))$", gmix);

    public static HashSet<string> GetEmbeddedExtensionsFromCsproj(string csprojPath)
    {
        var extensions = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            ".template",
            ".cshtml.cs",
            ".json",
            ".sql",
            ".md"
        };

        if (!File.Exists(csprojPath))
            return extensions;

        var doc = XDocument.Load(csprojPath);

        foreach (var include in doc.Descendants()
                     .Where(e => e.Name.LocalName == "EmbeddedResource")
                     .Select(e => e.Attribute("Include")?.Value)
                     .Where(v => !string.IsNullOrWhiteSpace(v)))
        {
            var matches = Regex.Matches(include, @"\.[a-zA-Z0-9\.]+\b");
            foreach (Match m in matches)
                if (m.Value.Length > 1)
                    extensions.Add(m.Value);
        }

        return extensions;
    }

    private static Regex BuildExtensionsRegex(IEnumerable<string> knownExtensions)
    {
        // Build alternation like: \.(?:template|cshtml\.cs|json|sql|\w+)
        var extPatterns = knownExtensions
            .Select(e => Regex.Escape(e.TrimStart('.')))
            .OrderByDescending(e => e.Length) // longest first (cshtml.cs before template)
            .Select(e => $@"\.{e}");

        var extensionGroup = string.Join("|", extPatterns.Concat(new[] { @"\.\w+" }));

        // Final regex
        var pattern =
            $@"^(?<qualified>.+?)\.(?<name>(?:(?<order>\d+)_)?.+?)(?<extension>{extensionGroup})$";

        return new Regex(pattern, gsix);
    }

    private static Regex BuildEmbeddedResourceRegex(IEnumerable<string> knownExtensions)
    {
        // Escape and join extensions like: (?:\.cshtml\.cs|\.template|\.json|\w+)
        var extPattern = string.Join("|",
            knownExtensions.Select(e => Regex.Escape(e.TrimStart('.')))
                .Select(e => $@"\.{e}")); // .template  or  .cshtml\.cs

        var fullPattern =
            $@"^(?<qualified>.+?)\.(?<name>(?:(?<order>\d+)_)?[^\s]+?)(?<extension>{extPattern}|\.\w+)$";

        return new Regex(fullPattern, gsix);
    }


    public static string ReadSourceFile(
        this Assembly myass,
        string[] resources,
        string name,
        bool debug = false)
    {
        if (debug)
        {
            Console.WriteLine($"{nameof(myass)} :>> {myass == null}");
            // Console.WriteLine($"{nameof(sourceAssembly)} :>> {sourceAssembly == null}");
            // Console.WriteLine($"{nameof(myass)} :>> {myass == null}");
        }

        if (debug)
            myass.Dump(nameof(myass));

        if (debug) Console.WriteLine($"loading source from assembly {myass.FullName}");


        var csprojPath = FindCsprojForAssembly(myass);
        var knownExts = GetEmbeddedExtensionsFromCsproj(csprojPath);

        var extensions_regex = BuildExtensionsRegex(knownExts);

        var source_files = resources
            .SelectMany(path => path.Extract<SourceFile>(extensions_regex))
            .OrderBy(file => file.Name)
            .ThenBy(file => file.Order > -1 ? file.Order : int.MaxValue)
            .ToArray();

        if (debug) source_files.Dump("verified source files");

        Console.WriteLine($"Looking for file '{name}'");

        string filename = Path.GetFileNameWithoutExtension(name);

        var file_match = source_files
            .SingleOrDefault(cf => cf.Name.Contains(filename));

        file_match.Dump(nameof(file_match));

        if (file_match.Name.IsEmpty())
            throw new FileNotFoundException($"{name} not found in {myass.GetName().Name}");

        Console.WriteLine("embedded full name:\n" + file_match.FullName);

        using var stream = myass.GetManifestResourceStream(file_match.FullName)!;

        using var reader = new StreamReader(stream);
        return reader.ReadToEnd();
    }

    private static string FindCsprojForAssembly(Assembly asm)
    {
        var asmPath = asm.Location;
        var dir = Path.GetDirectoryName(asmPath);
        while (dir != null)
        {
            var csprojs = Directory.GetFiles(dir, "*.csproj");
            if (csprojs.Length > 0)
                return csprojs.First(); // or be smarter with naming

            dir = Directory.GetParent(dir)?.FullName;
        }

        return string.Empty;
    }
}

public struct SourceFile
{
    public SourceFile()
    {
    }

    public string Name { get; set; } = string.Empty;
    public int Order { get; set; } = -1;
    public string Qualified { get; set; } = string.Empty;
    public string Extension { get; set; } = string.Empty;

    public string FullName => $"{Qualified}.{Name}{Extension}";
}

public static class DiagnosticExtensions
{
    /// <summary>
    /// Outputs your object to JSON
    /// Great for cases where we can't use traditional breakpoints.
    /// Can be used "in between" calls of virtually any object and still print.
    ///
    /// Quicker than CW or Debug.
    /// Can be used inside of Lambdas (Linq), IQueryables, DataTables, etc...
    /// Hooah!
    ///
    /// Usage:
    ///     myComplexObject.Dump("Orders").doSomethingElse();
    /// </summary>
    /// <typeparam name="T"></typeparam>
    /// <returns></returns>
    public static T Dump<T>(
        this T obj,
        string header = null,
        bool ignoreNulls = false,
        Action<string> printFn = null,
        [CallerMemberName] string method_name = ""
    )
    {
        // #if DEBUG  // This segment only runs when in Debug mode (never production)

        //This Assumes it's running a console app, if no function is provided.
        if (printFn == null)
        {
            if (Debugger.IsAttached)
            {
                printFn = (s) => Debug.WriteLine(s);
            }
            else
            {
                printFn = Console.WriteLine;
            }
        }

        if (obj != null)
        {
            // If it's a string, or overrides ToString() assume it's non-serializable.
            if (obj.OverridesToString())
            {
                printFn(obj.ToString());
                return obj;
            }

            var type = obj.GetType();

            // set header of JSON if not provided
            if (string.IsNullOrWhiteSpace(header))
                header = type.Name;

            var nested_types = type.GetNestedTypes().Select(t => t.Name);

            // The magic
            string prettyJson = JsonConvert.SerializeObject(
                obj,
                Formatting.Indented,
                new JsonSerializerSettings
                {
                    //ContractResolver = new WritablePropertiesOnlyResolver(),
                    ContractResolver = new ExcludeCalculatedResolver(),
                    Converters = new List<JsonConverter>
                    {
                        new StringEnumConverter(),
                    },
                    NullValueHandling = ignoreNulls
                        ? NullValueHandling.Ignore
                        : NullValueHandling.Include,
                    ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
                }
            );
            string nested_types_names = new StringBuilder()
                .AppendEach(nested_types, t => t, delimiter: ", ")
                .ToString();
            printFn($"{method_name}()\n{header}:\n\t{nested_types_names}\n\t\t{prettyJson}");
        }
        else
        {
            if (!string.IsNullOrWhiteSpace(header))
                printFn($"'{header}' is null.");
        }

        // #endif
        // return the original object.  This allows this function to be chained to (virtually) any object.
        return obj;
    }

    /// <summary>
    /// Source: https://stackoverflow.com/questions/18543482/is-there-a-way-to-ignore-get-only-properties-in-json-net-without-using-jsonignor
    /// </summary>
    sealed class WritablePropertiesOnlyResolver : DefaultContractResolver
    {
        protected override IList<JsonProperty> CreateProperties(
            Type type,
            MemberSerialization memberSerialization
        )
        {
            IList<JsonProperty> props = base.CreateProperties(type, memberSerialization);
            return props.Where(p => p.Writable).ToList();
        }
    }

    sealed class ExcludeCalculatedResolver : DefaultContractResolver
    {
        protected override JsonProperty CreateProperty(
            MemberInfo member,
            MemberSerialization memberSerialization
        )
        {
            var property = base.CreateProperty(member, memberSerialization);
            property.ShouldSerialize = _ => ShouldSerialize(member);
            return property;
        }

        internal static bool ShouldSerialize(MemberInfo memberInfo)
        {
            var propertyInfo = memberInfo as PropertyInfo;
            if (propertyInfo == null)
            {
                return false;
            }

            if (propertyInfo.SetMethod != null)
            {
                return true;
            }

            var getMethod = propertyInfo.GetMethod;
            return Attribute.GetCustomAttribute(getMethod, typeof(CompilerGeneratedAttribute))
                   != null;
        }
    }
}

public static class RegexExtensions
{
    public static RegexOptions gmix = RegexOptions.Compiled |
                                      RegexOptions.Multiline |
                                      RegexOptions.IgnoreCase |
                                      RegexOptions.IgnorePatternWhitespace;

    private static readonly IDictionary<Type, ICollection<PropertyInfo>>
        _propertyCache =
            new Dictionary<Type, ICollection<PropertyInfo>>();


    public static List<T> Extract<T>(
        this string text,
        Regex regex,
        bool enforce_exact_match = false,
        bool debug = false
    )
    {
        var collection = new List<T>();

        // If we get no text, throw if we're in devmode (debug == true)
        // If in prod, we want to probably return an empty set.
        if (string.IsNullOrWhiteSpace(text))
            return debug
                ? throw new ArgumentNullException(nameof(text))
                : collection;

        // Get the class properties so we can set values to them.
        var props = _propertyCache.TryGetProperties<T>().ToList();

        // If in prod, we want to probably return an empty set.
        if (props.Count == 0)
            return debug
                ? throw new ArgumentNullException(
                    $"No properties found for type {typeof(T).Name}"
                )
                : collection;

        var errors = new StringBuilder();

        // if (options == RegexOptions.None)
        //     options =
        //         RegexOptions.Compiled
        //         | RegexOptions.IgnoreCase
        //         | RegexOptions.ExplicitCapture
        //         | RegexOptions.Singleline
        //         | RegexOptions.IgnorePatternWhitespace;

        // var regex = new System.Text.RegularExpressions.Regex(regex_pattern, options, TimeSpan.FromMilliseconds(250));

        var matches = regex.Matches(text).Cast<Match>();

        matches.Aggregate(
            collection,
            (list, match) =>
            {
                if (!match.Success)
                {
                    errors.AppendLine(
                        $"No matches found! Could not extract a '{typeof(T).Name}' instance from regex pattern"
                    );

                    errors.AppendLine(text);

                    var missing = props
                        .Select(property => property.Name)
                        .Except(regex.GetGroupNames(),
                            StringComparer.OrdinalIgnoreCase)
                        .ToArray();

                    if (missing.Length > 0)
                    {
                        errors.AppendLine(
                            "Properties without a mapped Group:");
                        missing.Aggregate(errors,
                            (result, name) => result.AppendLine(name));
                    }

                    if (errors.Length > 0)
                        //throw new Exception(errors.ToString());
                        Debug.WriteLine(errors.ToString());
                }

                // This rolls up any and all exceptions encountered and rethrows them,
                // if we're trying to go for an absolute, no exceptions matching of Regex Groups to Class Properties:
                if (enforce_exact_match &&
                    match.Groups.Count - 1 != props.Count)
                {
                    errors.AppendLine(
                        $"{MethodBase.GetCurrentMethod().Name}() "
                        + $"WARNING: Number of Matched Groups ({match.Groups.Count}) "
                        + $"does not equal the number of properties for the given class '{typeof(T).Name}'({props.Count})!  "
                        + $"Check the class type and regex pattern for errors and try again."
                    );

                    errors.AppendLine("Values Parsed Successfully:");

                    for (int groupIndex = 1;
                         groupIndex < match.Groups.Count;
                         groupIndex++)
                    {
                        errors.Append(
                            $"{match.Groups[groupIndex].Value}\t");
                    }

                    errors.AppendLine();
                    Debug.WriteLine(errors.ToString());
                    //throw new Exception(errors.ToString());
                }

                object instance = Activator.CreateInstance(typeof(T));

                foreach (var property in props)
                {
                    // Get the raw string value that was matched by the Regex for each Group that was captured:
                    // string value = match
                    //     .Groups.Cast<Group>()
                    //     .SingleOrDefault(group =>
                    //         group.Name.Equals(property.Name, StringComparison.OrdinalIgnoreCase)
                    //     )
                    //     ?.Value.Trim();

                    GroupCollection groups = match.Groups;
                    string[]
                        groupNames =
                            regex
                                .GetGroupNames(); // Get the names of the groups

                    string value = string.Empty;
                    // Console.WriteLine("Named Groups:");
                    foreach (string groupName in groupNames)
                    {
                        if (groupName.Equals(property.Name,
                                StringComparison.OrdinalIgnoreCase))
                        {
                            value = groups[groupName].Value;
                            continue;
                        }
                    }

                    if (!string.IsNullOrWhiteSpace(value))
                    {
                        property.SetValue(
                            instance,
                            value: TypeDescriptor
                                .GetConverter(property.PropertyType)
                                .ConvertFrom(value),
                            index: null
                        );
                    }
                    else if (property.CanWrite)
                    {
                        property?.SetValue(instance, value: null,
                            index: null);
                    }
                }

                list.Add((T)instance);
                return list;
            }
        );

        return collection;
    }

    /// <summary>
    /// Takes a dictionary full of Regex patterns (or words) and swaps those values with whatever you set as the .Value.
    ///
    /// <usage>
    /// So, for example, a dictionary like this:
    ///
    /// var replacements = new Dictionary<..>{ { "\d+", "hello there!"}, {"Order", "66"}  }
    ///
    /// ... and a text string like this:
    ///
    /// string text = "Order was valued at $100.00";
    /// var altered_text = text.ReplaceAll(replacements);
    ///
    /// Should look something like:
    ///
    /// `66 was valued at $hello there!.hello there!`
    ///
    /// This can be used to do quick (but not comprehensive) replacements to format things like:
    /// * Random Unicode chars you don't want
    /// * Extra spaces
    /// * Other garbage like CLRF
    ///
    /// It does have a flaw in that the more you replace things, the less reliable it can be, especially if your replacements replace OTHER replacements.  So, tread lightly...
    /// </usage>
    /// </summary>
    public static string[] ReplaceAll(
        this string[] lines,
        Dictionary<string, string> replacementMap,
        RegexOptions options = RegexOptions.None
    )
    {
        if (options == RegexOptions.None)
            options = gmix;

        Dictionary<string, string> map = replacementMap.Aggregate(
            new Dictionary<string, string>(),
            (modified, next) =>
            {
                // Sometimes in JSON \ have to be represented in unicode.  This reverts it.
                string fixedKey = next.Key
                    .Replace("%5C", @"\")
                    .Replace(@"\\", @"\");

                string fixedValue =
                    Regex.Replace(
                        next.Value,
                        @"\""",
                        "'"
                    );

                modified.Add(fixedKey, fixedValue);
                return modified;
            }
        );

        List<string> results = new List<string>();

        foreach (string line in lines)
        {
            string modified = line;
            foreach (KeyValuePair<string, string> replacement in map)
            {
                modified = Regex.Replace(
                    modified,
                    replacement.Key,
                    replacement.Value,
                    options
                );
            }

            results.Add(modified);
        }

        return results.ToArray();
    }
}

public static class ReflectionExtensions
{
    public static ICollection<PropertyInfo> TryGetProperties<T>(
        this IDictionary<Type, ICollection<PropertyInfo>> property_cache,
        bool ignore_case = true,
        BindingFlags flags = BindingFlags.Default,
        params string[] exclusions
    )
    {
        ICollection<PropertyInfo> properties;
        var objType = typeof(T);

        lock (property_cache)
        {
            if (!property_cache.TryGetValue(objType, out properties))
            {
                // $"Prop not found for {objType.Name} so running reflection".Dump();

                var type_props = objType.GetProperties();

                var lowercased_prop_names = type_props.Select(p => p.Name.ToLowerInvariant());

                var joined_names = lowercased_prop_names.Except(exclusions);

                properties = type_props
                    .Where(property =>
                        property.CanWrite && joined_names.Contains(property.Name.ToLowerInvariant())
                    )
                    .ToList();

                property_cache.Add(objType, properties);

                // property_cache.Count.Dump("propcache size");
            }
        }

        return properties;
    }
}

//
// namespace CodeMechanic.Embeds.SourceGen;
// [Generator]
// public sealed class EmbeddedResourcesGenerator : IIncrementalGenerator
// {
//     public void Initialize(IncrementalGeneratorInitializationContext context)
//     {
//         context.RegisterPostInitializationOutput(ctx =>
//         {
//             var source = """
//                          // <auto-generated />
//                          #nullable enable
//
//                          namespace CodeMechanic.Embeds
//                          {
//                              /// <summary>
//                              /// Strongly-typed embedded resources.
//                              /// Generated by CodeMechanic.Embeds.SourceGen
//                              /// </summary>
//                              public static partial class Embedded
//                              {
//                                  public static readonly SourceFile PackageReferenceTemplate = new()
//                                  {
//                                      Name = "package_reference.template",
//                                      Qualified = "sfapp.templates",
//                                      Extension = ".template"
//                                  };
//
//                                  public static readonly SourceFile RazorAppTemplate = new()
//                                  {
//                                      Name = "razor.app.template",
//                                      Qualified = "sfapp.templates",
//                                      Extension = ".template"
//                                  };
//
//                                  static Embedded()
//                                  {
//                                      // Optional: remove if you have a static ctor already
//                                      // Console.WriteLine("✅ CodeMechanic Embedded resources loaded!");
//                                  }
//                              }
//                          }
//                          """;
//
//             ctx.AddSource("CodeMechanic_Embeds_Resources.g.cs",
//                 SourceText.From(source, Encoding.UTF8));
//         });
//     }
// }

// [Generator]
// public sealed class EmbeddedResourcesGenerator : IIncrementalGenerator
// {
//     public void Initialize(IncrementalGeneratorInitializationContext context)
//     {
//         context.RegisterPostInitializationOutput(ctx =>
//         {
//             var source = """
//                          // <auto-generated />
//                          #nullable enable
//
//                          namespace CodeMechanic.Embeds
//                          {
//                              /// <summary>
//                              /// Auto-generated strongly-typed embedded resource references.
//                              /// Generated by CodeMechanic.Embeds.SourceGen v1.0.5
//                              /// </summary>
//                              public static partial class Embedded
//                              {
//                                  public static readonly SourceFile HelloWorldTemplate = new()
//                                  {
//                                      Name = "HelloWorld",
//                                      Qualified = "CodeMechanic.Embeds",
//                                      Extension = ".template"
//                                  };
//
//                                  // No static constructor here — avoids conflict with your real one
//                              }
//                          }
//                          """;
//
//             ctx.AddSource("CodeMechanic_Embeds_HelloWorld.g.cs",
//                 SourceText.From(source, Encoding.UTF8));
//         });
//     }
// }

//
// [Generator]
// public sealed class EmbeddedResourcesGenerator : IIncrementalGenerator
// {
//     public void Initialize(IncrementalGeneratorInitializationContext context)
//     {
//         context.RegisterPostInitializationOutput(ctx =>
//         {
//             var source = """
//                          // <auto-generated />
//                          #nullable enable
//
//                          using System;
//
//                          namespace CodeMechanic.Embeds
//                          {
//                              public static partial class Embedded
//                              {
//                                  public static readonly SourceFile HelloWorldTemplate = new()
//                                  {
//                                      Name = "HelloWorld",
//                                      Qualified = "CodeMechanic.Embeds",
//                                      Extension = ".template"
//                                  };
//
//                                  static Embedded()
//                                  {
//                                      Console.WriteLine("🚀 CodeMechanic.Embeds.SourceGen v1.0.0 - HelloWorld generator loaded from BaGetter!");
//                                  }
//                              }
//                          }
//                          """;
//
//             ctx.AddSource("CodeMechanic_Embeds_HelloWorld.g.cs",
//                 SourceText.From(source, Encoding.UTF8));
//         });
//     }
// }

//
// [Generator]
// public sealed class EmbeddedResourcesGenerator : IIncrementalGenerator
// {
//     public void Initialize(IncrementalGeneratorInitializationContext context)
//     {
//         // HelloWorld placeholder - no csproj parsing yet
//         context.RegisterPostInitializationOutput(static ctx =>
//         {
//             var source = GenerateHelloWorld();
//             ctx.AddSource("CodeMechanic_Embeds_HelloWorld.g.cs",
//                 SourceText.From(source, Encoding.UTF8));
//         });
//     }
//
//     private static string GenerateHelloWorld()
//     {
//         return """
//                // <auto-generated />
//                #nullable enable
//
//                using System;
//
//                namespace CodeMechanic.Embeds
//                {
//                    /// <summary>
//                    /// CodeMechanic.Embeds.SourceGen is alive and kicking on your BaGetter feed!
//                    /// </summary>
//                    public static partial class Embedded
//                    {
//                        public static readonly SourceFile HelloWorldTemplate = new()
//                        {
//                            Name = "HelloWorld",
//                            Qualified = "CodeMechanic.Embeds",
//                            Extension = ".template",
//                            // FullName will be constructed correctly by your existing logic
//                        };
//
//                        static Embedded()
//                        {
//                            Console.WriteLine("🎉 CodeMechanic.Embeds.SourceGen HelloWorld loaded successfully!");
//                        }
//                    }
//                }
//                """;
//     }
// }

public static class StringBuilderExtensions
{
    public static StringBuilder AsStringBuilder(this string text) => new StringBuilder(text);

    public static StringBuilder RemoveFromEnd(this StringBuilder sb, int number_of_characters) =>
        sb.Length >= number_of_characters ? sb.With(s => s.Length -= number_of_characters) : sb;

    public static StringBuilder Prepend(this StringBuilder sb, string line) => sb.Insert(0, line);

    /// <summary>
    /// Append only when a condition is met
    /// </summary>
    public static StringBuilder AppendIf<T>(
        this StringBuilder builder,
        Func<T, bool> predicate,
        params T[] values
    )
    {
        var list = values ?? Enumerable.Empty<T>();
        foreach (var value in list.Where(value => predicate(value)))
        {
            builder.Append(value);
        }

        return builder;
    }

    [Obsolete("Use the one without the space delimiter")]
    public static StringBuilder AppendEach<T>(
        this StringBuilder builder,
        IEnumerable<T> collection,
        Func<T, string> selector = null,
        string delimiter = " "
    )
    {
        return collection
            .Aggregate(
                builder,
                (_, next_value) =>
                {
                    selector = selector.TryGet(selector_fn => selector_fn);
                    string next_line = selector(next_value);
                    builder.Append($"{next_line}{delimiter}");
                    return builder;
                }
            )
            .RemoveFromEnd(delimiter.Length);
    }
}

public static class TypeExtensions
{
    /// <summary>
    /// Update properties on a long, nested object easily.
    ///
    /// Usage:
    ///   your.ultralarge.complex.infragistics.winforms.grid.table.row.With(row=> {
    ///      row.Text = "hello there!"
    ///      row.Color = "blue"
    ///      ...
    ///      };
    ///</summary>
    public static T With<T>(this T obj, Action<T> patch)
    {
        patch(obj);
        return obj;
    }


    /// <summary>
    /// (VS 2022/ 2015 SHIM)
    /// This is a replacement for the '?.' null coaslesce or 'Elvis operator'.
    /// This is here because VB can implicitly convert NULL object values like the Request["some_param"], but C# will not.
    /// This also prevents trying to make if-null-else logic in our ASPX files, and instead lets us call one method to make a type conversion, like so:
    ///
    /// <%= r["orderdatetime"].TryGet(odt=>odt.ToString().ToDateTime().Value) %>
    /// </summary>
    public static TValue TryGet<TObject, TValue>(
        this TObject obj,
        Func<TObject, TValue> getter,
        TValue fallback = default
    )
        where TObject : class
    {
        // TODO: this doesn't properly get the correct type on the lefthand side when TOject actually is a string.
        if (typeof(TObject) == typeof(string))
        {
            string value = obj as string;
            return string.IsNullOrWhiteSpace(value) ? fallback : getter(obj);
        }

        return obj == null ? fallback : getter(obj);
    }
}

/// <summary>
/// A series of VB string methods as C# extension methods
/// Credit: https://kodify.net/csharp/strings/left-right-mid/
/// </summary>
public static class StringExtensions
{
    public static bool IsEmpty(this string text) => string.IsNullOrWhiteSpace(text);

    public static bool IsNotEmpty(this string text) => !text.IsEmpty();

    public static bool NotEmpty(this string text) => IsNotEmpty(text);

    public static bool OverridesToString(this object v)
    {
        return v.ToString() != v.GetType().ToString();
    }

    public static string Rollup(this string[] lines_of_code)
    {
        return lines_of_code.Aggregate(
                new StringBuilder(),
                (sb, next) =>
                {
                    sb.AppendLine(next.TrimEnd());
                    return sb;
                })
            .ToString();
    }

    public static string Rollup(this string[] lines_of_code, string start,
        string end)
    {
        return lines_of_code.Aggregate(
                new StringBuilder(start),
                (sb, next) =>
                {
                    sb.AppendLine(next);
                    return sb;
                })
            .With(sb => sb.AppendLine(end))
            .ToString();
    }
}
